### ISSUE TITLE
Non-primitive Annotation attributes

### ISSUE THREAD

**Issue by computerlyrik** [highsource/jaxb2-annotate-plugin#10]
Hey.

First: thanks for the great work.

Second: following problem:

This is working like a charm:
`<annox:annotate target="field">@javax.persistence.OneToMany</annox:annotate>`

And this
 `<annox:annotate target="field">@javax.persistence.OneToMany(cascade=javax.persistence.CascadeType.ALL)</annox:annotate>`

gives me the following error:

Caused by: org.jvnet.annox.parser.exception.ValueParseException: Could not parse the value [javax.persistence.CascadeType.ALL] into the target class [[Ljavax.persistence.CascadeType;].
	at org.jvnet.annox.parser.java.visitor.ExpressionVisitor.visitDefault(ExpressionVisitor.java:20)
	at org.jvnet.annox.parser.java.visitor.ExpressionVisitor.visitDefault(ExpressionVisitor.java:9)
	at org.jvnet.annox.japa.parser.ast.visitor.AbstractGenericExpressionVisitor.visit(AbstractGenericExpressionVisitor.java:305)
	at japa.parser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:58)
	at org.jvnet.annox.parser.XArrayAnnotationFieldParser.parse(XArrayAnnotationFieldParser.java:97)

**What am i doing wrong?**
	... 42 more

**Comment by highsource** [comment]
`cascade` is an array, try `{javax.persistence.CascadeType.ALL}` instead of just `javax.persistence.CascadeType.ALL`.

**Comment by computerlyrik** [comment]
You are very fast. And 100% correct.

Thank you.
