### ISSUE TITLE
<annox:annotate> not generating annotations

### ISSUE THREAD

**Issue by dhanuap2011** [highsource/jaxb2-annotate-plugin#41]
Hi,
I want to annotate a generated jaxb class with annotation @XMLSeeAlso.
Project is getting built successfully, however no annotation is actually added in the generated class.
Please find attached binding file, XSD file and POM.
XSD is very simple with just 1 complex type.
[jaxb.zip](https://github.com/highsource/jaxb2-annotate-plugin/files/1244712/jaxb.zip)
Please assist.

BTW my maven version is 3.3.9 and java version is 1.8 and below is the maven log.
[MvnLogs.txt](https://github.com/highsource/jaxb2-annotate-plugin/files/1244716/MvnLogs.txt)

Regards,
Dhananjay.

**Comment by highsource** [comment]
Start by moving to a more recent version. 0.6.4 which you use is very old.

Next, you use jaxb2-maven-plugin so you should ask there how to activate an XJC plugin. My instructions are based on maven-jaxb2-plugin which is a different Maven plugin for JAXB.

**Comment by dhanuap2011** [comment]
Hi! Thanks for the reply.
I updated the versions and also switched to maven-jaxb2-plugin, but now I am getting some error.
Please find attached zip for POM, XSD, binding file and maven logs
[mvn-jaxb2.zip](https://github.com/highsource/jaxb2-annotate-plugin/files/1244880/mvn-jaxb2.zip)
Could you please assist.

**Comment by highsource** [comment]
Now you're using a very old version of `maven-jaxb2-plugin` (0.9.1).

**Comment by dhanuap2011** [comment]
I switched to 0.13.2 but now I am getting error :- A required class is missing: org/jvnet/mjiip/v_2_2/XJC22Mojo.
Probably this is again old version for some artifact.
Is it possible to provide any sample POM with all dependencies with correct versions that will work with maven 3.3.9 and java 1.8.

**Comment by highsource** [comment]
Releases include sample projects:

https://github.com/highsource/jaxb2-annotate-plugin/releases/tag/1.0.3

**Comment by dhanuap2011** [comment]
Strange.......I downloaded this example but I am still facing the same exception even for the given example.
I don't understand what am I missing.
Only diff is, I am using 
                                           <plugin>
							<groupId>org.jvnet.jaxb2_commons</groupId>
							<artifactId>jaxb2-basics-annotate</artifactId>
							<version>1.0.2</version>
						</plugin>
I could not find 1.0.3 for jaxb2-basics-annotate
Exception is:
java.lang.TypeNotPresentException: Type org.jvnet.mjiip.v_2.XJC2Mojo not present
        at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:147)
        at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
        at org.eclipse.sisu.bean.BeanScheduler$Activator.onProvision(BeanScheduler.java:176)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
        at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
        at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NoClassDefFoundError: org/jvnet/mjiip/v_2_2/XJC22Mojo
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:401)
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:139)
        ... 42 more
Caused by: java.lang.ClassNotFoundException: org.jvnet.mjiip.v_2_2.XJC22Mojo
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 57 more

**Comment by highsource** [comment]
I've just downloaded and ran `mvn clean install`. Worked fine, below is my log:
[std.txt](https://github.com/highsource/jaxb2-annotate-plugin/files/1246700/std.txt)

**Comment by highsource** [comment]
I can't build your project since it has wrong directory structure (for instance configured with schema directory `src/main/xsd`, but schema is in the root of the archive) and also references parent `com.amdocs.oss.sfo.nlt:XSD` which I don't have.

**Comment by highsource** [comment]
Hm, seems like version 1.0.3 was not released to the central Maven repo. How very interesting.
